{{- if .Values.global.enableOpenshiftRouter }}
{{- $local := get .Values.global "local" | default dict }}
{{- $exports := get $local "export" | default list }}
{{- range $export := $exports }}
{{- $ports := $export.ports | default $.Values.global.defaultServicePorts }}
{{- range $port := $ports }}
{{- $host := include "hostname.withPort" (dict "hostname" $export.hostname "port" $port.number) }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: export-{{ printf "%s" $export.hostname | replace "." "-" }}-{{ $port.number }}
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ $host }}
  to:
    kind: Service
    name: {{ .Values.global.gateways.ingress.serviceName | default "istio-eastwestgateway" }}
    weight: 100
  port:
    targetPort: {{ .Values.global.ingress.portName | default "tls" }}
  tls:
    termination: passthrough
  wildcardPolicy: None
{{- end }}
{{- end }}
{{- end }}
